DistributedRaytracer: Main.cpp OBJReader.cpp Mesh.cpp MeshData.cpp BoundingBox.cpp Face.cpp Camera.cpp Raytracer.cpp Ray.cpp Image.cpp Triangle.cpp Material.cpp MTLReader.cpp Utilities.cpp
	g++ -o trace Main.cpp OBJReader.cpp Mesh.cpp MeshData.cpp BoundingBox.cpp Face.cpp Camera.cpp Raytracer.cpp Ray.cpp Image.cpp Triangle.cpp Material.cpp MTLReader.cpp Utilities.cpp -g -O3
