DistributedRaytracer: Main.cpp OBJReader.cpp Mesh.cpp BoundingBox.cpp Face.cpp Camera.cpp Raytracer.cpp Ray.cpp Image.cpp
	g++ -o trace Main.cpp OBJReader.cpp Mesh.cpp BoundingBox.cpp Face.cpp Camera.cpp Raytracer.cpp Ray.cpp Image.cpp -g
