DistributedRaytracer: Main.cpp OBJReader.cpp Mesh.cpp MeshData.cpp BoundingBox.cpp Face.cpp Camera.cpp Raytracer.cpp Ray.cpp Image.cpp Triangle.cpp
	g++ -o trace Main.cpp OBJReader.cpp Mesh.cpp MeshData.cpp BoundingBox.cpp Face.cpp Camera.cpp Raytracer.cpp Ray.cpp Image.cpp Triangle.cpp -g
